version: "3"
services:
  server:
    image: backend
    container_name: backend
    ports:
      - "8080:8080"
    build:
      context: .                         
      dockerfile: Dockerfile           
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/db_springboot_backend?useSSL=false&useJDBCComplaintTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - spring.datasource.username=sa
      - spring.datasource.password=1234
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0.31
    container_name: mysqldb
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_springboot_backend
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  springmysql-net: